### ISSUE TITLE
UserServiceTest 통합테스트 -> 단위테스트 수정

### ISSUE THREAD

**Issue by junsoo90** [f-lab-edu/running-mate#36]
통합테스트 진행시 redis 오류로 인해 진행 안되기 때문에, 단위 테스트로 수정

**Comment by gamzagamza** [comment]
음 redis 오류로인해 이미 통합테스트 과정에서 오류가나서 이를 회피하기위해 통합테스트를 모두 없애버리는게 맞는걸까요?
근본적인 원인을 찾아 해결하지 않으면 추후 다시 또 같은 문제에 직면해야 할 것으로 생각됩니다.

통합테스트 자체가 문제라기 보단 Redis서버와 커넥션을 맺는 Bean생성 시 발생하는 문제입니다.
로컬 환경에서는 이미 Redis가 설치되어있기 때문에 테스트 진행 시 연결에 문제가 없어 테스트에 통과하지만
Github Action CI에서 빌드와 테스트를 진행하는 환경에는 로컬에 Redis가 설치되어 있지 않아 connection을 맺지못해 문제가
발생하는 것 입니다.
