### ISSUE TITLE
회원 로그인 / 로그아웃

### ISSUE THREAD

**Issue by junsoo90** [f-lab-edu/running-mate#7]
회원 로그인
회원 로그아웃

**Comment by gamzagamza** [comment]
회원정보 CRUD 라는 제목보다는 회원가입 기능 개발, 로그인 기능개발, 비밀번호 찾기 기능 개발 등으로 나누어 이슈 등록하시는건 어떨까요?
회원정보 CRUD는 기능에대한 통합적인 의미보다는 단순히 데이터 입력 수정 삭제 등을 의미하는거같은 제목인거같아서요!
